import type { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: 'Adidas Classic Hoodie',
    slug: 'adidas-classic-hoodie',
    category: 'Clothing',
    image: '../images/p1.jpg',
    price: 2500,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.7,
    numReviews: 32,
    description: 'Sudadera cómoda y duradera para uso diario',
  },
  {
    name: 'Polo Ralph Lauren T-Shirt',
    slug: 'polo-ralph-lauren-tshirt',
    category: 'Clothing',
    image: '../images/p2.jpg',
    price: 3200,
    countInStock: 12,
    brand: 'Ralph Lauren',
    rating: 4.8,
    numReviews: 21,
    description: 'Camiseta clásica de alta calidad',
  },
  {
    name: 'Jordan Retro 4 Sneakers',
    slug: 'jordan-retro-4',
    category: 'Shoes',
    image: '../images/p3.jpg',
    price: 14500,
    countInStock: 5,
    brand: 'Nike',
    rating: 4.9,
    numReviews: 45,
    description: 'Tenis edición retro muy buscados en RD',
  },
  {
    name: 'Faja Colombiana Levanta Glúteos',
    slug: 'faja-colombiana-levanta-gluteos',
    category: 'Underwear',
    image: '../images/p4.jpg',
    price: 1800,
    countInStock: 25,
    brand: 'Ann Chery',
    rating: 4.6,
    numReviews: 28,
    description: 'Ideal para moldear la figura y realzar glúteos',
  },
  {
    name: 'Gorra New Era NY Yankees',
    slug: 'new-era-ny-yankees',
    category: 'Accessories',
    image: '../images/p5.jpg',
    price: 2200,
    countInStock: 18,
    brand: 'New Era',
    rating: 4.7,
    numReviews: 19,
    description: 'Gorra original estilo urbano muy popular en RD',
  }
];
